"""Unique constraint for roles

Revision ID: 037a99eaf526
Revises: 44ed75766a60
Create Date: 2016-07-10 14:18:46.455411

"""

# revision identifiers, used by Alembic.
revision = '037a99eaf526'
down_revision = '44ed75766a60'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'roles_users', ['user_id', 'role_id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'roles_users', type_='unique')
    ### end Alembic commands ###
