"""no_error_message_index

Revision ID: 05fe2c0fd896
Revises: 457af3698a
Create Date: 2016-01-05 15:11:56.537934

"""

# revision identifiers, used by Alembic.
revision = '05fe2c0fd896'
down_revision = '457af3698a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_error_message', table_name='error')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_error_message', 'error', ['message'], unique=False)
    ### end Alembic commands ###
