"""empty message

Revision ID: 10a65d2b5cc
Revises: 5281164d11e
Create Date: 2015-06-21 21:22:29.371387

"""

# revision identifiers, used by Alembic.
revision = '10a65d2b5cc'
down_revision = '5281164d11e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_session_user_id'), 'session', ['user_id'], unique=False)
    op.drop_index('ix_session_user_name', table_name='session')
    op.create_foreign_key(None, 'session', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('session', 'user_name')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('user_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'session', type_='foreignkey')
    op.create_index('ix_session_user_name', 'session', ['user_name'], unique=False)
    op.drop_index(op.f('ix_session_user_id'), table_name='session')
    op.drop_column('session', 'user_id')
    ### end Alembic commands ###
