"""empty message

Revision ID: 139c415d0be3
Revises: 19eb8cf75f5f
Create Date: 2015-05-31 21:52:33.397174

"""

# revision identifiers, used by Alembic.
revision = '139c415d0be3'
down_revision = '19eb8cf75f5f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('run_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('token', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_run_token_token'), 'run_token', ['token'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_run_token_token'), table_name='run_token')
    op.drop_table('run_token')
    ### end Alembic commands ###
