"""Add test parameters

Revision ID: 13f7bd549e82
Revises: b4df2f8b8ae0
Create Date: 2017-01-08 23:18:18.939698

"""

# revision identifiers, used by Alembic.
revision = '13f7bd549e82'
down_revision = 'b4df2f8b8ae0'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test', sa.Column('parameters', postgresql.JSONB(), nullable=True))
    op.create_index('ix_test_session_id_start_time', 'test', ['session_id', 'start_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_test_session_id_start_time', table_name='test')
    op.drop_column('test', 'parameters')
    # ### end Alembic commands ###
