"""empty message

Revision ID: 156a97c783
Revises: 50e5bc2d542
Create Date: 2015-07-23 15:48:16.309327

"""

# revision identifiers, used by Alembic.
revision = '156a97c783'
down_revision = '50e5bc2d542'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('archived', sa.Boolean(), server_default='false', nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session', 'archived')
    ### end Alembic commands ###
