"""empty message

Revision ID: 19eb8cf75f5f
Revises: 4574723cfb4b
Create Date: 2015-05-31 12:51:26.434745

"""

# revision identifiers, used by Alembic.
revision = '19eb8cf75f5f'
down_revision = '4574723cfb4b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute("insert into role(name) values ('admin')")
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
