"""Add scm branches

Revision ID: 19f878f363bf
Revises: ea0a1b8dd57f
Create Date: 2017-08-21 09:22:50.339166

"""

# revision identifiers, used by Alembic.
revision = '19f878f363bf'
down_revision = 'ea0a1b8dd57f'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test', sa.Column('scm_local_branch', sa.String(length=256), nullable=True))
    op.add_column('test', sa.Column('scm_remote_branch', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test', 'scm_remote_branch')
    op.drop_column('test', 'scm_local_branch')
    # ### end Alembic commands ###
