"""empty message

Revision ID: 1a416935ea4
Revises: 1e29891921b
Create Date: 2015-06-27 21:45:30.970158

"""

# revision identifiers, used by Alembic.
revision = '1a416935ea4'
down_revision = '1e29891921b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_session_product_name', table_name='session')
    op.drop_index('ix_session_product_revision', table_name='session')
    op.drop_index('ix_session_product_version', table_name='session')
    op.drop_column('session', 'product_revision')
    op.drop_column('session', 'product_name')
    op.drop_column('session', 'product_version')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('product_version', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.add_column('session', sa.Column('product_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.add_column('session', sa.Column('product_revision', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.create_index('ix_session_product_version', 'session', ['product_version'], unique=False)
    op.create_index('ix_session_product_revision', 'session', ['product_revision'], unique=False)
    op.create_index('ix_session_product_name', 'session', ['product_name'], unique=False)
    ### end Alembic commands ###
