"""stats

Revision ID: 1b9db367bae
Revises: 4888e69ac49
Create Date: 2015-12-25 23:35:29.212969

"""

# revision identifiers, used by Alembic.
revision = '1b9db367bae'
down_revision = '4888e69ac49'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.Float(), nullable=True),
    sa.Column('stat_db_size', sa.BIGINT(), server_default='0', nullable=True),
    sa.Column('stat_num_new_sessions', sa.Integer(), server_default='0', nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stat_timestamp'), 'stat', [sa.text('timestamp desc')], unique=False)
    op.create_index(op.f('ix_session_end_time'), 'session', ['end_time'], unique=False)
    op.create_index(op.f('ix_session_next_keepalive'), 'session', ['next_keepalive'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_session_next_keepalive'), table_name='session')
    op.drop_index(op.f('ix_session_end_time'), table_name='session')
    op.drop_index(op.f('ix_stat_timestamp'), table_name='stat')
    op.drop_table('stat')
    ### end Alembic commands ###
