"""related_entities

Revision ID: 1c3eba8b7b0
Revises: 45b9dcd7daa
Create Date: 2015-12-03 08:43:01.483828

"""

# revision identifiers, used by Alembic.
revision = '1c3eba8b7b0'
down_revision = '45b9dcd7daa'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('related_entity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=256), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_id'], ['test.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_related_entity_session_id'), 'related_entity', ['session_id'], unique=False)
    op.create_index(op.f('ix_related_entity_test_id'), 'related_entity', ['test_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_related_entity_test_id'), table_name='related_entity')
    op.drop_index(op.f('ix_related_entity_session_id'), table_name='related_entity')
    op.drop_table('related_entity')
    ### end Alembic commands ###
