"""empty message

Revision ID: 1e29891921b
Revises: ff4e53a41b
Create Date: 2015-06-25 22:11:19.390220

"""

# revision identifiers, used by Alembic.
revision = '1e29891921b'
down_revision = 'ff4e53a41b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('num_errors', sa.Integer(), nullable=True))
    op.add_column('session', sa.Column('status', sa.String(length=20), nullable=False))
    op.create_index(op.f('ix_session_status'), 'session', ['status'], unique=False)
    op.add_column('test', sa.Column('status', sa.String(length=20), nullable=False))
    op.create_index(op.f('ix_test_status'), 'test', ['status'], unique=False)
    op.drop_column('test', 'skipped')
    op.drop_column('test', 'interrupted')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test', sa.Column('interrupted', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('test', sa.Column('skipped', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_test_status'), table_name='test')
    op.drop_column('test', 'status')
    op.drop_index(op.f('ix_session_status'), table_name='session')
    op.drop_column('session', 'status')
    op.drop_column('session', 'num_errors')
    ### end Alembic commands ###
