"""interactive marker

Revision ID: 1ec58c8eef0
Revises: 315e71d436e
Create Date: 2015-10-25 21:52:54.843330

"""

# revision identifiers, used by Alembic.
revision = '1ec58c8eef0'
down_revision = '315e71d436e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test', sa.Column('is_interactive', sa.Boolean(), server_default='FALSE', nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test', 'is_interactive')
    ### end Alembic commands ###
