"""Drop old related entity table

Revision ID: 22e789c2b650
Revises: 0361dbb4d96f
Create Date: 2016-12-18 22:33:57.188580

"""

# revision identifiers, used by Alembic.
revision = '22e789c2b650'
down_revision = '0361dbb4d96f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('related_entity')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('related_entity',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('type', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('test_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('session_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], name='related_entity_session_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_id'], ['test.id'], name='related_entity_test_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='related_entity_pkey')
    )
    # ### end Alembic commands ###
