"""empty message

Revision ID: 2500fd549a85
Revises: f0048e89917
Create Date: 2015-02-19 16:30:12.436336

"""

# revision identifiers, used by Alembic.
revision = '2500fd549a85'
down_revision = 'f0048e89917'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('error',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=True),
    sa.Column('traceback', postgresql.JSON(), nullable=True),
    sa.Column('exception_type', sa.String(length=256), nullable=True),
    sa.Column('exception', sa.String(length=256), nullable=True),
    sa.Column('timestamp', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['test_id'], ['test.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_error_exception'), 'error', ['exception'], unique=False)
    op.create_index(op.f('ix_error_exception_type'), 'error', ['exception_type'], unique=False)
    op.create_index(op.f('ix_error_test_id'), 'error', ['test_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_error_test_id'), table_name='error')
    op.drop_index(op.f('ix_error_exception_type'), table_name='error')
    op.drop_index(op.f('ix_error_exception'), table_name='error')
    op.drop_table('error')
    ### end Alembic commands ###
