"""Fix timespans

Revision ID: 2799ab20163b
Revises: cc153c80cbab
Create Date: 2018-10-02 20:57:00.974077

"""

# revision identifiers, used by Alembic.
revision = '2799ab20163b'
down_revision = 'cc153c80cbab'

from alembic import op
import sqlalchemy as sa


def upgrade():
    op.execute('''
UPDATE "session" SET timespan = tstzrange(lower(timespan), to_timestamp(next_keepalive))
WHERE upper(timespan) IS NULL and next_keepalive IS NOT NULL
''')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
