"""Adding updated_at to session and test models

Revision ID: 27cdd554eb2f
Revises: 534d739192db
Create Date: 2018-03-12 10:46:58.798105

"""

# revision identifiers, used by Alembic.
revision = '27cdd554eb2f'
down_revision = '534d739192db'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_index('ix_session_updated_at', 'session', [sa.text('updated_at ASC')], unique=False, postgresql_where=sa.text('updated_at IS NOT NULL'))
    op.add_column('test', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_index('ix_test_updated_at', 'test', [sa.text('updated_at ASC')], unique=False, postgresql_where=sa.text('updated_at IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_test_updated_at', table_name='test')
    op.drop_column('test', 'updated_at')
    op.drop_index(op.f('ix_session_updated_at'), table_name='session')
    op.drop_column('session', 'updated_at')
    # ### end Alembic commands ###
