"""Add replication

Revision ID: 28c2f1c6aa15
Revises: 27cdd554eb2f
Create Date: 2018-04-09 13:10:50.009002

"""

# revision identifiers, used by Alembic.
revision = '28c2f1c6aa15'
down_revision = '27cdd554eb2f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('replication',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_type', sa.String(length=50), server_default='elastic-search', nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('index_name', sa.String(length=1024), nullable=False),
    sa.Column('username', sa.String(length=1024), nullable=True),
    sa.Column('password', sa.String(length=1024), nullable=True),
    sa.Column('paused', sa.Boolean(), server_default='FALSE', nullable=True),
    sa.Column('untimed_done', sa.Boolean(), server_default='FALSE', nullable=True),
    sa.Column('backlog_remaining', sa.Integer(), nullable=True),
    sa.Column('last_replicated_timestamp', sa.DateTime(), nullable=True),
    sa.Column('last_replicated_id', sa.Integer(), nullable=True),
    sa.Column('last_chunk_finished', sa.Float(), server_default='0', nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('avg_per_second', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('replication')
    # ### end Alembic commands ###
