"""empty message

Revision ID: 2aeb533be9a
Revises: 156a97c783
Create Date: 2015-08-10 22:35:19.172510

"""

# revision identifiers, used by Alembic.
revision = '2aeb533be9a'
down_revision = '156a97c783'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.Float(), nullable=True),
    sa.Column('test_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_id'], ['test.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_session_id'), 'activity', ['session_id'], unique=False)
    op.create_index(op.f('ix_activity_test_id'), 'activity', ['test_id'], unique=False)
    op.create_index(op.f('ix_activity_user_id'), 'activity', ['user_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_activity_user_id'), table_name='activity')
    op.drop_index(op.f('ix_activity_test_id'), table_name='activity')
    op.drop_index(op.f('ix_activity_session_id'), table_name='activity')
    op.drop_table('activity')
    ### end Alembic commands ###
