"""Initial

Revision ID: 31a5269d02d
Revises: None
Create Date: 2015-10-01 14:30:16.396919

"""

# revision identifiers, used by Alembic.
revision = '31a5269d02d'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('error',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('traceback', postgresql.JSON(), nullable=True),
    sa.Column('exception_type', sa.String(length=256), nullable=True),
    sa.Column('message', sa.String(length=256), nullable=True),
    sa.Column('timestamp', sa.Float(), nullable=True),
    sa.Column('is_failure', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_error_exception_type'), 'error', ['exception_type'], unique=False)
    op.create_index(op.f('ix_error_message'), 'error', ['message'], unique=False)
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('subject',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_information',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=1024), nullable=True),
    sa.Column('class_name', sa.String(length=256), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_information_class_name'), 'test_information', ['class_name'], unique=False)
    op.create_index(op.f('ix_test_information_file_name'), 'test_information', ['file_name'], unique=False)
    op.create_index(op.f('ix_test_information_name'), 'test_information', ['name'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.Float(), nullable=True),
    sa.Column('deleted', sa.Boolean(), server_default='false', nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comment_user_id'), 'comment', ['user_id'], unique=False)
    op.create_table('product_version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=256), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'version')
    )
    op.create_index(op.f('ix_product_version_product_id'), 'product_version', ['product_id'], unique=False)
    op.create_table('roles_users',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE')
    )
    op.create_table('run_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_run_token_token'), 'run_token', ['token'], unique=True)
    op.create_table('session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('logical_id', sa.String(length=256), nullable=True),
    sa.Column('start_time', sa.Float(), nullable=True),
    sa.Column('end_time', sa.Float(), nullable=True),
    sa.Column('hostname', sa.String(length=100), nullable=True),
    sa.Column('archived', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('investigated', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('total_num_tests', sa.Integer(), nullable=True),
    sa.Column('num_failed_tests', sa.Integer(), nullable=True),
    sa.Column('num_error_tests', sa.Integer(), nullable=True),
    sa.Column('num_skipped_tests', sa.Integer(), nullable=True),
    sa.Column('num_finished_tests', sa.Integer(), nullable=True),
    sa.Column('num_warnings', sa.Integer(), server_default='0', nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('real_user_id', sa.Integer(), nullable=True),
    sa.Column('num_errors', sa.Integer(), nullable=True),
    sa.Column('num_failures', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['real_user_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_logical_id'), 'session', ['logical_id'], unique=False)
    op.create_index(op.f('ix_session_status'), 'session', ['status'], unique=False)
    op.create_index(op.f('ix_session_user_id'), 'session', ['user_id'], unique=False)
    op.create_table('product_revision',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_version_id', sa.Integer(), nullable=False),
    sa.Column('revision', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['product_version_id'], ['product_version.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_version_id', 'revision')
    )
    op.create_index(op.f('ix_product_revision_product_version_id'), 'product_revision', ['product_version_id'], unique=False)
    op.create_table('session_comment',
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('comment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['comment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ondelete='CASCADE')
    )
    op.create_table('session_error',
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('error_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['error_id'], ['error.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ondelete='CASCADE')
    )
    op.create_table('session_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('key', sa.String(length=1024), nullable=False),
    sa.Column('metadata_item', postgresql.JSONB(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_metadata_session_id'), 'session_metadata', ['session_id'], unique=False)
    op.create_table('test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_info_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('logical_id', sa.String(length=256), nullable=True),
    sa.Column('start_time', sa.Float(), nullable=True),
    sa.Column('end_time', sa.Float(), nullable=True),
    sa.Column('num_errors', sa.Integer(), nullable=True),
    sa.Column('num_failures', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('skip_reason', sa.Text(), nullable=True),
    sa.Column('num_warnings', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_info_id'], ['test_information.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_logical_id'), 'test', ['logical_id'], unique=False)
    op.create_index(op.f('ix_test_session_id'), 'test', ['session_id'], unique=False)
    op.create_index(op.f('ix_test_status'), 'test', ['status'], unique=False)
    op.create_index(op.f('ix_test_test_info_id'), 'test', ['test_info_id'], unique=False)
    op.create_table('activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.Float(), nullable=True),
    sa.Column('test_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_id'], ['test.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_session_id'), 'activity', ['session_id'], unique=False)
    op.create_index(op.f('ix_activity_test_id'), 'activity', ['test_id'], unique=False)
    op.create_index(op.f('ix_activity_user_id'), 'activity', ['user_id'], unique=False)
    op.create_table('subject_instance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('revision_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['revision_id'], ['product_revision.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subject_instance_revision_id'), 'subject_instance', ['revision_id'], unique=False)
    op.create_index(op.f('ix_subject_instance_subject_id'), 'subject_instance', ['subject_id'], unique=False)
    op.create_table('test_comment',
    sa.Column('test_id', sa.Integer(), nullable=True),
    sa.Column('comment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['comment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_id'], ['test.id'], ondelete='CASCADE')
    )
    op.create_table('test_error',
    sa.Column('test_id', sa.Integer(), nullable=True),
    sa.Column('error_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['error_id'], ['error.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_id'], ['test.id'], ondelete='CASCADE')
    )
    op.create_table('test_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=True),
    sa.Column('key', sa.String(length=1024), nullable=False),
    sa.Column('metadata_item', postgresql.JSONB(), nullable=True),
    sa.ForeignKeyConstraint(['test_id'], ['test.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_metadata_test_id'), 'test_metadata', ['test_id'], unique=False)
    op.create_table('warning',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('filename', sa.String(length=2048), nullable=True),
    sa.Column('lineno', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_id'], ['test.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warning_session_id'), 'warning', ['session_id'], unique=False)
    op.create_index(op.f('ix_warning_test_id'), 'warning', ['test_id'], unique=False)
    op.create_table('session_subject',
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subject_instance.id'], ondelete='CASCADE')
    )

    op.execute("insert into role(name) values ('admin')")
    op.execute("INSERT INTO role(name) VALUES ('proxy')")
    op.execute("insert into role(name) values ('moderator')")
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session_subject')
    op.drop_index(op.f('ix_warning_test_id'), table_name='warning')
    op.drop_index(op.f('ix_warning_session_id'), table_name='warning')
    op.drop_table('warning')
    op.drop_index(op.f('ix_test_metadata_test_id'), table_name='test_metadata')
    op.drop_table('test_metadata')
    op.drop_table('test_error')
    op.drop_table('test_comment')
    op.drop_index(op.f('ix_subject_instance_subject_id'), table_name='subject_instance')
    op.drop_index(op.f('ix_subject_instance_revision_id'), table_name='subject_instance')
    op.drop_table('subject_instance')
    op.drop_index(op.f('ix_activity_user_id'), table_name='activity')
    op.drop_index(op.f('ix_activity_test_id'), table_name='activity')
    op.drop_index(op.f('ix_activity_session_id'), table_name='activity')
    op.drop_table('activity')
    op.drop_index(op.f('ix_test_test_info_id'), table_name='test')
    op.drop_index(op.f('ix_test_status'), table_name='test')
    op.drop_index(op.f('ix_test_session_id'), table_name='test')
    op.drop_index(op.f('ix_test_logical_id'), table_name='test')
    op.drop_table('test')
    op.drop_index(op.f('ix_session_metadata_session_id'), table_name='session_metadata')
    op.drop_table('session_metadata')
    op.drop_table('session_error')
    op.drop_table('session_comment')
    op.drop_index(op.f('ix_product_revision_product_version_id'), table_name='product_revision')
    op.drop_table('product_revision')
    op.drop_index(op.f('ix_session_user_id'), table_name='session')
    op.drop_index(op.f('ix_session_status'), table_name='session')
    op.drop_index(op.f('ix_session_logical_id'), table_name='session')
    op.drop_table('session')
    op.drop_index(op.f('ix_run_token_token'), table_name='run_token')
    op.drop_table('run_token')
    op.drop_table('roles_users')
    op.drop_index(op.f('ix_product_version_product_id'), table_name='product_version')
    op.drop_table('product_version')
    op.drop_index(op.f('ix_comment_user_id'), table_name='comment')
    op.drop_table('comment')
    op.drop_table('user')
    op.drop_index(op.f('ix_test_information_name'), table_name='test_information')
    op.drop_index(op.f('ix_test_information_file_name'), table_name='test_information')
    op.drop_index(op.f('ix_test_information_class_name'), table_name='test_information')
    op.drop_table('test_information')
    op.drop_table('subject')
    op.drop_table('role')
    op.drop_table('product')
    op.drop_index(op.f('ix_error_message'), table_name='error')
    op.drop_index(op.f('ix_error_exception_type'), table_name='error')
    op.drop_table('error')
    ### end Alembic commands ###
