"""empty message

Revision ID: 36b001176e75
Revises: 3958451c7305
Create Date: 2015-04-30 17:05:35.415066

"""

# revision identifiers, used by Alembic.
revision = '36b001176e75'
down_revision = '3958451c7305'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_error',
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('error_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['error_id'], ['error.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ondelete='CASCADE')
    )
    op.create_table('test_error',
    sa.Column('test_id', sa.Integer(), nullable=True),
    sa.Column('error_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['error_id'], ['error.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_id'], ['test.id'], ondelete='CASCADE')
    )
    op.drop_index('ix_error_test_id', table_name='error')
    op.drop_constraint(u'error_test_id_fkey', 'error', type_='foreignkey')
    op.drop_column(u'error', 'test_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'error', sa.Column('test_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(u'error_test_id_fkey', 'error', 'test', ['test_id'], ['id'])
    op.create_index('ix_error_test_id', 'error', ['test_id'], unique=False)
    op.drop_table('test_error')
    op.drop_table('session_error')
    ### end Alembic commands ###
