"""add comment edited property

Revision ID: 383eac3634aa
Revises: 6389fc7012b2
Create Date: 2016-12-27 22:05:42.442083

"""

# revision identifiers, used by Alembic.
revision = '383eac3634aa'
down_revision = '6389fc7012b2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('edited', sa.Boolean(), server_default='false', nullable=True))
    op.create_index(op.f('ix_session_entity_entity_id'), 'session_entity', ['entity_id'], unique=False)
    op.create_index(op.f('ix_session_entity_session_id'), 'session_entity', ['session_id'], unique=False)
    op.create_index(op.f('ix_test_entity_entity_id'), 'test_entity', ['entity_id'], unique=False)
    op.create_index(op.f('ix_test_entity_test_id'), 'test_entity', ['test_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_entity_test_id'), table_name='test_entity')
    op.drop_index(op.f('ix_test_entity_entity_id'), table_name='test_entity')
    op.drop_index(op.f('ix_session_entity_session_id'), table_name='session_entity')
    op.drop_index(op.f('ix_session_entity_entity_id'), table_name='session_entity')
    op.drop_column('comment', 'edited')
    # ### end Alembic commands ###
