"""empty message

Revision ID: 38a4fcc8b6e
Revises: 4c580b39b03e
Create Date: 2015-04-18 18:30:35.971969

"""

# revision identifiers, used by Alembic.
revision = '38a4fcc8b6e'
down_revision = '4c580b39b03e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test', sa.Column('test_conclusion', sa.String(length=256), nullable=True))
    op.create_index(op.f('ix_test_test_conclusion'), 'test', ['test_conclusion'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_test_conclusion'), table_name='test')
    op.drop_column('test', 'test_conclusion')
    ### end Alembic commands ###
