"""Warnings

Revision ID: 38b56426138
Revises: 4f5cc367429
Create Date: 2015-09-20 21:22:49.168261

"""

# revision identifiers, used by Alembic.
revision = '38b56426138'
down_revision = '4f5cc367429'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warning',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('filename', sa.String(length=2048), nullable=True),
    sa.Column('lineno', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_id'], ['test.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warning_session_id'), 'warning', ['session_id'], unique=False)
    op.create_index(op.f('ix_warning_test_id'), 'warning', ['test_id'], unique=False)
    op.add_column('session', sa.Column('num_warnings', sa.Integer(), server_default='0', nullable=False))
    op.add_column('test', sa.Column('num_warnings', sa.Integer(), server_default='0', nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test', 'num_warnings')
    op.drop_column('session', 'num_warnings')
    op.drop_index(op.f('ix_warning_test_id'), table_name='warning')
    op.drop_index(op.f('ix_warning_session_id'), table_name='warning')
    op.drop_table('warning')
    ### end Alembic commands ###
