"""empty message

Revision ID: 3958451c7305
Revises: 38a4fcc8b6e
Create Date: 2015-04-20 17:11:18.537838

"""

# revision identifiers, used by Alembic.
revision = '3958451c7305'
down_revision = '38a4fcc8b6e'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('metadata_item', postgresql.JSONB(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_metadata_session_id'), 'session_metadata', ['session_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_session_metadata_session_id'), table_name='session_metadata')
    op.drop_table('session_metadata')
    ### end Alembic commands ###
