"""user_activity

Revision ID: 3c7d98cd5bd
Revises: 58a877020ce
Create Date: 2015-11-23 09:16:27.860770

"""

# revision identifiers, used by Alembic.
revision = '3c7d98cd5bd'
down_revision = '58a877020ce'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_activity', sa.Float(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_activity')
    ### end Alembic commands ###
