"""Infrastructure saving

Revision ID: 3df7cc3e0f5b
Revises: 4a7e99a064bb
Create Date: 2016-02-23 22:54:46.792891

"""

# revision identifiers, used by Alembic.
revision = '3df7cc3e0f5b'
down_revision = '4a7e99a064bb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('infrastructure', sa.String(length=50), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session', 'infrastructure')
    ### end Alembic commands ###
