"""empty message

Revision ID: 44becdc6831
Revises: 4de4cbc0ba5
Create Date: 2015-06-28 21:54:21.656828

"""

# revision identifiers, used by Alembic.
revision = '44becdc6831'
down_revision = '4de4cbc0ba5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_information',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=1024), nullable=False),
    sa.Column('class_name', sa.String(length=256), nullable=True),
    sa.Column('function_name', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_information_class_name'), 'test_information', ['class_name'], unique=False)
    op.create_index(op.f('ix_test_information_file_name'), 'test_information', ['file_name'], unique=False)
    op.create_index(op.f('ix_test_information_function_name'), 'test_information', ['function_name'], unique=False)
    op.add_column('test', sa.Column('test_info_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_test_test_info_id'), 'test', ['test_info_id'], unique=False)
    op.drop_index('ix_test_name', table_name='test')
    op.create_foreign_key(None, 'test', 'test_information', ['test_info_id'], ['id'])
    op.drop_column('test', 'name')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test', sa.Column('name', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'test', type_='foreignkey')
    op.create_index('ix_test_name', 'test', ['name'], unique=False)
    op.drop_index(op.f('ix_test_test_info_id'), table_name='test')
    op.drop_column('test', 'test_info_id')
    op.drop_index(op.f('ix_test_information_function_name'), table_name='test_information')
    op.drop_index(op.f('ix_test_information_file_name'), table_name='test_information')
    op.drop_index(op.f('ix_test_information_class_name'), table_name='test_information')
    op.drop_table('test_information')
    ### end Alembic commands ###
