"""App config in DB

Revision ID: 44ed75766a60
Revises: 952293dcee6b
Create Date: 2016-07-09 22:07:16.922290

"""

# revision identifiers, used by Alembic.
revision = '44ed75766a60'
down_revision = '952293dcee6b'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_config',
    sa.Column('key', sa.String(length=256), nullable=False),
    sa.Column('value', postgresql.JSONB(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('app_config')
    ### end Alembic commands ###
