"""empty message

Revision ID: 457af3698a
Revises: 1b9db367bae
Create Date: 2016-01-04 10:27:11.318782

"""

# revision identifiers, used by Alembic.
revision = '457af3698a'
down_revision = '1b9db367bae'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('num_comments', sa.Integer(), nullable=True))
    op.add_column('test', sa.Column('num_comments', sa.Integer(), nullable=True))
    ### end Alembic commands ###
    op.execute("UPDATE test SET num_comments = (SELECT count(*) FROM comment WHERE comment.test_id=test.id)""")
    op.execute("UPDATE session SET num_comments = (SELECT count(*) FROM comment WHERE comment.session_id=session.id)""")


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test', 'num_comments')
    op.drop_column('session', 'num_comments')
    ### end Alembic commands ###
