"""unique_subject_name

Revision ID: 45b9dcd7daa
Revises: 3c7d98cd5bd
Create Date: 2015-11-28 22:29:23.499079

"""

# revision identifiers, used by Alembic.
revision = '45b9dcd7daa'
down_revision = '3c7d98cd5bd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_subject_name'), 'subject', ['name'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subject_name'), table_name='subject')
    ### end Alembic commands ###
