"""empty message

Revision ID: 46b820968e12
Revises: 3958451c7305
Create Date: 2015-04-21 16:44:40.760478

"""

# revision identifiers, used by Alembic.
revision = '46b820968e12'
down_revision = '3958451c7305'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_error',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('traceback', postgresql.JSON(), nullable=True),
    sa.Column('exception_type', sa.String(length=256), nullable=True),
    sa.Column('exception', sa.String(length=256), nullable=True),
    sa.Column('timestamp', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_error_exception'), 'session_error', ['exception'], unique=False)
    op.create_index(op.f('ix_session_error_exception_type'), 'session_error', ['exception_type'], unique=False)
    op.create_index(op.f('ix_session_error_session_id'), 'session_error', ['session_id'], unique=False)


    op.drop_index(op.f('ix_error_test_id'), table_name='error')
    op.drop_index(op.f('ix_error_exception_type'), table_name='error')
    op.drop_index(op.f('ix_error_exception'), table_name='error')
    op.rename_table('error', 'test_error')
    op.create_index(op.f('ix_test_error_exception'), 'test_error', ['exception'], unique=False)
    op.create_index(op.f('ix_test_error_exception_type'), 'test_error', ['exception_type'], unique=False)
    op.create_index(op.f('ix_test_error_session_id'), 'test_error', ['test_id'], unique=False)
    op.execute('ALTER TABLE test_error RENAME CONSTRAINT "error_test_id_fkey" TO "test_error_test_id_fkey";')

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_error_exception'), table_name='test_error')
    op.drop_index(op.f('ix_test_error_exception_type'), table_name='test_error')
    op.drop_index(op.f('ix_test_error_session_id'), table_name='test_error')
    op.rename_table('test_error', 'error')
    op.create_index(op.f('ix_error_exception'), 'error', ['exception'], unique=False)
    op.create_index(op.f('ix_error_exception_type'), 'error', ['exception_type'], unique=False)
    op.create_index(op.f('ix_error_session_id'), 'error', ['test_id'], unique=False)
    op.execute('ALTER TABLE error RENAME CONSTRAINT "test_error_test_id_fkey" TO "error_test_id_fkey";')

    op.drop_index(op.f('ix_session_error_session_id'), table_name='session_error')
    op.drop_index(op.f('ix_session_error_exception_type'), table_name='session_error')
    op.drop_index(op.f('ix_session_error_exception'), table_name='session_error')
    op.drop_table('session_error')
    ### end Alembic commands ###
