"""session_warnings_count

Revision ID: 47360dc61f2
Revises: 59a51bddd6
Create Date: 2015-11-17 22:06:29.587520

"""

# revision identifiers, used by Alembic.
revision = '47360dc61f2'
down_revision = '59a51bddd6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('num_test_warnings', sa.Integer(), server_default='0', nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session', 'num_test_warnings')
    ### end Alembic commands ###
