"""indices

Revision ID: 4888e69ac49
Revises: 23ed581b6dc
Create Date: 2015-12-22 23:07:18.886827

"""

# revision identifiers, used by Alembic.
revision = '4888e69ac49'
down_revision = '23ed581b6dc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_session_start_time', 'session', [sa.text('start_time DESC')], unique=False)
    op.create_index('ix_test_start_time', 'test', [sa.text('start_time DESC')], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_test_start_time', table_name='test')
    op.drop_index('ix_session_start_time', table_name='session')
    ### end Alembic commands ###
