"""Add num_interrupted_tests to session

Revision ID: 4a0ad548d6cb
Revises: 13f7bd549e82
Create Date: 2017-03-20 11:11:11.862482

"""

# revision identifiers, used by Alembic.
revision = '4a0ad548d6cb'
down_revision = '13f7bd549e82'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('num_interrupted_tests', sa.Integer(), server_default='0', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session', 'num_interrupted_tests')
    # ### end Alembic commands ###
