"""System load

Revision ID: 4a7e99a064bb
Revises: 05fe2c0fd896
Create Date: 2016-02-13 22:45:10.834860

"""

# revision identifiers, used by Alembic.
revision = '4a7e99a064bb'
down_revision = '05fe2c0fd896'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stat', sa.Column('stat_system_load_avg', sa.Float(), server_default='0', nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stat', 'stat_system_load_avg')
    ### end Alembic commands ###
