"""empty message

Revision ID: 4aa5981096b
Revises: 5b5c6699d4
Create Date: 2015-08-15 23:26:54.211305

"""

# revision identifiers, used by Alembic.
revision = '4aa5981096b'
down_revision = '5b5c6699d4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_session_edited_status', table_name='session')
    op.drop_column('session', 'edited_status')
    op.drop_index('ix_test_edited_status', table_name='test')
    op.drop_column('test', 'edited_status')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test', sa.Column('edited_status', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.create_index('ix_test_edited_status', 'test', ['edited_status'], unique=False)
    op.add_column('session', sa.Column('edited_status', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.create_index('ix_session_edited_status', 'session', ['edited_status'], unique=False)
    ### end Alembic commands ###
