"""Add Error.is_interruption

Revision ID: 4af90bfc558d
Revises: f0bfc3f425c7
Create Date: 2017-10-19 13:58:05.413915

"""

# revision identifiers, used by Alembic.
revision = '4af90bfc558d'
down_revision = 'f0bfc3f425c7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('error', sa.Column('is_interruption', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('error', 'is_interruption')
    # ### end Alembic commands ###
