"""empty message

Revision ID: 4c580b39b03e
Revises: f0048e89917
Create Date: 2015-03-30 16:10:52.710860

"""

# revision identifiers, used by Alembic.
revision = '4c580b39b03e'
down_revision = 'f0048e89917'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('num_error_tests', sa.Integer(), nullable=True))
    op.add_column('session', sa.Column('num_failed_tests', sa.Integer(), nullable=True))
    op.add_column('session', sa.Column('num_finished_tests', sa.Integer(), nullable=True))
    op.add_column('session', sa.Column('num_skipped_tests', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session', 'num_skipped_tests')
    op.drop_column('session', 'num_finished_tests')
    op.drop_column('session', 'num_failed_tests')
    op.drop_column('session', 'num_error_tests')
    ### end Alembic commands ###
