"""Add redis stats

Revision ID: 4c7f1d4c0eae
Revises: e265d0623907
Create Date: 2016-04-10 13:51:16.165094

"""

# revision identifiers, used by Alembic.
revision = '4c7f1d4c0eae'
down_revision = 'e265d0623907'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stat', sa.Column('stat_num_redis_keys', sa.Integer(), server_default='0', nullable=True))
    op.add_column('stat', sa.Column('stat_redis_memory_usage', sa.Integer(), server_default='0', nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stat', 'stat_redis_memory_usage')
    op.drop_column('stat', 'stat_num_redis_keys')
    ### end Alembic commands ###
