"""Real user ids

Revision ID: 4f5cc367429
Revises: b83ca2cbc0
Create Date: 2015-09-14 22:06:30.363378

"""

# revision identifiers, used by Alembic.
revision = '4f5cc367429'
down_revision = 'b83ca2cbc0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('real_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'session', 'user', ['real_user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('test_test_info_id_fkey', 'test', type_='foreignkey')
    op.create_foreign_key(None, 'test', 'test_information', ['test_info_id'], ['id'], ondelete='CASCADE')
    op.execute("INSERT INTO role(name) VALUES ('proxy')")
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM role WHERE name = 'proxy'")
    op.drop_constraint(None, 'test', type_='foreignkey')
    op.create_foreign_key('test_test_info_id_fkey', 'test', 'test_information', ['test_info_id'], ['id'])
    op.drop_constraint(None, 'session', type_='foreignkey')
    op.drop_column('session', 'real_user_id')
    ### end Alembic commands ###
