"""empty message

Revision ID: 50e5bc2d542
Revises: b5dc55d034
Create Date: 2015-07-08 23:43:46.706923

"""

# revision identifiers, used by Alembic.
revision = '50e5bc2d542'
down_revision = 'b5dc55d034'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('num_failures', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session', 'num_failures')
    ### end Alembic commands ###
