"""empty message

Revision ID: 5281164d11e
Revises: bc2a439f06
Create Date: 2015-06-19 22:48:08.682822

"""

# revision identifiers, used by Alembic.
revision = '5281164d11e'
down_revision = 'bc2a439f06'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_metadata', sa.Column('key', sa.String(length=1024), nullable=False))
    op.add_column('test_metadata', sa.Column('key', sa.String(length=1024), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_metadata', 'key')
    op.drop_column('session_metadata', 'key')
    ### end Alembic commands ###
