"""Add interruption counters

Revision ID: 534d739192db
Revises: 4af90bfc558d
Create Date: 2017-10-19 15:21:47.063851

"""

# revision identifiers, used by Alembic.
revision = '534d739192db'
down_revision = '4af90bfc558d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('num_interruptions', sa.Integer(), nullable=True))
    op.add_column('test', sa.Column('num_interruptions', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test', 'num_interruptions')
    op.drop_column('session', 'num_interruptions')
    # ### end Alembic commands ###
