"""comment_session_id_test_id

Revision ID: 59a51bddd6
Revises: ed88fd10bc
Create Date: 2015-11-16 09:00:05.057323

"""

# revision identifiers, used by Alembic.
revision = '59a51bddd6'
down_revision = 'ed88fd10bc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_comment')
    op.drop_table('session_comment')
    op.add_column('comment', sa.Column('session_id', sa.Integer(), nullable=True))
    op.add_column('comment', sa.Column('test_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_comment_session_id'), 'comment', ['session_id'], unique=False)
    op.create_index(op.f('ix_comment_test_id'), 'comment', ['test_id'], unique=False)
    op.create_foreign_key(None, 'comment', 'test', ['test_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'comment', 'session', ['session_id'], ['id'], ondelete='CASCADE')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_index(op.f('ix_comment_test_id'), table_name='comment')
    op.drop_index(op.f('ix_comment_session_id'), table_name='comment')
    op.drop_column('comment', 'test_id')
    op.drop_column('comment', 'session_id')
    op.create_table('session_comment',
    sa.Column('session_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('comment_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['comment.id'], name='session_comment_comment_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], name='session_comment_session_id_fkey', ondelete='CASCADE')
    )
    op.create_table('test_comment',
    sa.Column('test_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('comment_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['comment.id'], name='test_comment_comment_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_id'], ['test.id'], name='test_comment_test_id_fkey', ondelete='CASCADE')
    )
    ### end Alembic commands ###
