"""empty message

Revision ID: 59aa5c4328f
Revises: 1cf822ad388
Create Date: 2015-08-12 22:55:54.163739

"""

# revision identifiers, used by Alembic.
revision = '59aa5c4328f'
down_revision = '1cf822ad388'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('investigated', sa.Boolean(), server_default='false', nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session', 'investigated')
    ### end Alembic commands ###
