"""empty message

Revision ID: 5a22533f1041
Revises: 4937cca3706f
Create Date: 2014-12-11 09:19:03.423404

"""

# revision identifiers, used by Alembic.
revision = '5a22533f1041'
down_revision = '4937cca3706f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test', sa.Column('interrupted', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test', 'interrupted')
    ### end Alembic commands ###
