"""empty message

Revision ID: 5a2b4a340d4
Revises: 139c415d0be3
Create Date: 2015-06-04 09:44:30.581571

"""

# revision identifiers, used by Alembic.
revision = '5a2b4a340d4'
down_revision = '139c415d0be3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('run_token', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('run_token', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    ### end Alembic commands ###
