"""empty message

Revision ID: 5b5c6699d4
Revises: 59aa5c4328f
Create Date: 2015-08-14 07:56:09.822880

"""

# revision identifiers, used by Alembic.
revision = '5b5c6699d4'
down_revision = '59aa5c4328f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test', sa.Column('skip_reason', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test', 'skip_reason')
    ### end Alembic commands ###
