"""Index user fields in lowercase

Revision ID: 6389fc7012b2
Revises: 22e789c2b650
Create Date: 2016-12-21 13:45:05.189545

"""

# revision identifiers, used by Alembic.
revision = '6389fc7012b2'
down_revision = '22e789c2b650'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
