"""Add session.ttl_seconds field

Revision ID: 7de4c23aaddd
Revises: 9fec9a1192c8
Create Date: 2017-09-07 17:54:01.658414

"""

# revision identifiers, used by Alembic.
revision = '7de4c23aaddd'
down_revision = '9fec9a1192c8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('ttl_seconds', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session', 'ttl_seconds')
    # ### end Alembic commands ###
