"""Add indexing for roles

Revision ID: 82b34e2777a4
Revises: 037a99eaf526
Create Date: 2016-07-10 14:26:54.218715

"""

# revision identifiers, used by Alembic.
revision = '82b34e2777a4'
down_revision = '037a99eaf526'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_roles_users_user_id', 'roles_users', ['user_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_roles_users_user_id', table_name='roles_users')
    ### end Alembic commands ###
