"""Add test updated_at,id index

Revision ID: 8f864a7768f8
Revises: 2799ab20163b
Create Date: 2019-01-17 13:13:59.216981

"""

# revision identifiers, used by Alembic.
revision = '8f864a7768f8'
down_revision = '2799ab20163b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_test_updated_at_id', 'test', [sa.text('updated_at ASC'), sa.text('id ASC')], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_test_updated_at_id', table_name='test')
    # ### end Alembic commands ###
