"""Adding is_parent_session and child_id to session model

Revision ID: 90a07ecb7dc7
Revises: 9c5e1cfd0e8a
Create Date: 2017-06-08 10:31:13.121197

"""

# revision identifiers, used by Alembic.
revision = '90a07ecb7dc7'
down_revision = '9c5e1cfd0e8a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('child_id', sa.String(length=20), nullable=True))
    op.add_column('session', sa.Column('is_parent_session', sa.Boolean(), server_default='FALSE', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session', 'is_parent_session')
    op.drop_column('session', 'child_id')
    # ### end Alembic commands ###
