"""Traceback URLs

Revision ID: 952293dcee6b
Revises: bd2b2746e4ed
Create Date: 2016-06-26 22:24:28.959648

"""

# revision identifiers, used by Alembic.
revision = '952293dcee6b'
down_revision = 'bd2b2746e4ed'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('error', sa.Column('traceback_url', sa.String(length=2048), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('error', 'traceback_url')
    ### end Alembic commands ###
