"""Add session.delete_at field

Revision ID: 9fec9a1192c8
Revises: e9430e3e444f
Create Date: 2017-08-22 16:16:38.094146

"""

# revision identifiers, used by Alembic.
revision = '9fec9a1192c8'
down_revision = 'e9430e3e444f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('delete_at', sa.Float(), nullable=True))
    op.create_index('ix_session_delete_at', 'session', ['delete_at'], unique=False, postgresql_where=sa.text('delete_at IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_session_delete_at', table_name='session')
    op.drop_column('session', 'delete_at')
    # ### end Alembic commands ###
