"""Index related entities

Revision ID: a155bf913e34
Revises: 9306b5950ba7
Create Date: 2016-11-30 21:45:50.261651

"""

# revision identifiers, used by Alembic.
revision = 'a155bf913e34'
down_revision = '9306b5950ba7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_related_entity_session_id_name', 'related_entity', ['session_id', 'name'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_related_entity_session_id_name', table_name='related_entity')
    ### end Alembic commands ###
