"""Add missing index

Revision ID: a9b7d64c8cd7
Revises: 90a07ecb7dc7
Create Date: 2017-06-21 15:43:36.203598

"""

# revision identifiers, used by Alembic.
revision = 'a9b7d64c8cd7'
down_revision = '90a07ecb7dc7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_session_label_session_id_label_id', 'session_label', ['session_id', 'label_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_session_label_session_id_label_id', table_name='session_label')
    # ### end Alembic commands ###
