"""Add subject activity

Revision ID: a9f4a63afe1a
Revises: efb299afcfe9
Create Date: 2016-03-30 08:57:27.236264

"""

# revision identifiers, used by Alembic.
revision = 'a9f4a63afe1a'
down_revision = 'efb299afcfe9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subject', sa.Column('last_activity', sa.Float(), nullable=True))
    op.create_index(op.f('ix_subject_last_activity'), 'subject', ['last_activity'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subject_last_activity'), table_name='subject')
    op.drop_column('subject', 'last_activity')
    ### end Alembic commands ###
