"""empty message

Revision ID: b5dc55d034
Revises: 1a3b32e0927
Create Date: 2015-07-08 23:21:49.435173

"""

# revision identifiers, used by Alembic.
revision = 'b5dc55d034'
down_revision = '1a3b32e0927'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('error', sa.Column('is_failure', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('error', 'is_failure')
    ### end Alembic commands ###
