"""empty message

Revision ID: b83ca2cbc0
Revises: 4aa5981096b
Create Date: 2015-08-16 07:19:29.832655

"""

# revision identifiers, used by Alembic.
revision = 'b83ca2cbc0'
down_revision = '4aa5981096b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute("insert into role(name) values ('moderator')")
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
