"""empty message

Revision ID: bc2a439f06
Revises: 5a2b4a340d4
Create Date: 2015-06-15 22:25:42.018113

"""

# revision identifiers, used by Alembic.
revision = 'bc2a439f06'
down_revision = '5a2b4a340d4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('total_num_tests', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session', 'total_num_tests')
    ### end Alembic commands ###
