"""Index user first_last_name

Revision ID: c9193bcb6894
Revises: 4c7f1d4c0eae
Create Date: 2016-06-14 21:17:00.032938

"""

# revision identifiers, used by Alembic.
revision = 'c9193bcb6894'
down_revision = '4c7f1d4c0eae'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_user_first_name'), 'user', ['first_name'], unique=False)
    op.create_index(op.f('ix_user_last_name'), 'user', ['last_name'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_last_name'), table_name='user')
    op.drop_index(op.f('ix_user_first_name'), table_name='user')
    ### end Alembic commands ###
