"""Add time+status.lower indices to test and session

Revision ID: ce7eef7a094c
Revises: 5423cc7c9f9a
Create Date: 2017-05-14 16:25:41.490187

"""

# revision identifiers, used by Alembic.
revision = 'ce7eef7a094c'
down_revision = '5423cc7c9f9a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
