"""User full name

Revision ID: cfa12a3eed60
Revises: 3df7cc3e0f5b
Create Date: 2016-03-05 23:21:31.102906

"""

# revision identifiers, used by Alembic.
revision = 'cfa12a3eed60'
down_revision = '3df7cc3e0f5b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('first_name', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('last_name', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'first_name')
    ### end Alembic commands ###
