"""Add fatal errors support

Revision ID: d378ba47afba
Revises: f276be9ca1be
Create Date: 2017-07-02 14:54:21.604197

"""

# revision identifiers, used by Alembic.
revision = 'd378ba47afba'
down_revision = 'f276be9ca1be'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('has_fatal_errors', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session', 'has_fatal_errors')
    # ### end Alembic commands ###
