"""Fix test indices

Revision ID: d5e936a5835e
Revises: 6ba5e3ab38a0
Create Date: 2017-07-31 21:44:23.202503

"""

# revision identifiers, used by Alembic.
revision = 'd5e936a5835e'
down_revision = '6ba5e3ab38a0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_test_status_lower_start_time', 'test', [sa.text('lower(status::text)'), sa.text('start_time DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_test_status_lower_start_time', 'test')
    # ### end Alembic commands ###
