"""Add traceback size field

Revision ID: dafc141fefb9
Revises: fd8a0947699c
Create Date: 2019-04-01 08:36:14.360589

"""

# revision identifiers, used by Alembic.
revision = 'dafc141fefb9'
down_revision = 'fd8a0947699c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('error', sa.Column('traceback_size', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('error', 'traceback_size')
    # ### end Alembic commands ###
