"""Add subject ordinal numbers to preserve order

Revision ID: ea0a1b8dd57f
Revises: 9c00de5646cd
Create Date: 2017-08-16 13:20:41.635660

"""

# revision identifiers, used by Alembic.
revision = 'ea0a1b8dd57f'
down_revision = '9c00de5646cd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE SEQUENCE subject_seq')
    op.add_column('session_subject', sa.Column('ordinal', sa.Integer(), server_default=sa.text("nextval('subject_seq')"), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP SEQUENCE subject_seq')
    op.drop_column('session_subject', 'ordinal')
    # ### end Alembic commands ###
