"""unique_constraint_on_test_logical_id

Revision ID: ebb488aa9a5e
Revises: 13f7bd549e82
Create Date: 2017-03-06 16:38:18.341470

"""

# revision identifiers, used by Alembic.
revision = 'ebb488aa9a5e'
down_revision = '4a0ad548d6cb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_test_logical_id', table_name='test')
    op.create_index(op.f('ix_test_logical_id'), 'test', ['logical_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_logical_id'), table_name='test')
    op.create_index('ix_test_logical_id', 'test', ['logical_id'], unique=False)
    # ### end Alembic commands ###
