"""keepalive

Revision ID: ed88fd10bc
Revises: 1ec58c8eef0
Create Date: 2015-10-28 22:00:18.331330

"""

# revision identifiers, used by Alembic.
revision = 'ed88fd10bc'
down_revision = '1ec58c8eef0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('keepalive_interval', sa.Integer(), nullable=True))
    op.add_column('session', sa.Column('next_keepalive', sa.Float(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session', 'next_keepalive')
    op.drop_column('session', 'keepalive_interval')
    ### end Alembic commands ###
