"""Add in_pdb field

Revision ID: efb299afcfe9
Revises: cfa12a3eed60
Create Date: 2016-03-22 11:19:24.829725

"""

# revision identifiers, used by Alembic.
revision = 'efb299afcfe9'
down_revision = 'cfa12a3eed60'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('in_pdb', sa.Boolean(), server_default='FALSE', nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session', 'in_pdb')
    ### end Alembic commands ###
