"""empty message

Revision ID: f0048e89917
Revises: 5a22533f1041
Create Date: 2015-01-31 16:53:51.405879

"""

# revision identifiers, used by Alembic.
revision = 'f0048e89917'
down_revision = '5a22533f1041'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('test_metadata', 'metadata_item', type_=postgresql.JSONB())
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('test_metadata', 'metadata_item', type_=postgresql.JSON())
    ### end Alembic commands ###
