"""empty message

Revision ID: f0048e89917
Revises: 5a22533f1041
Create Date: 2015-01-31 16:53:51.405879

"""

# revision identifiers, used by Alembic.
revision = 'f0048e89917'
down_revision = '5a22533f1041'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE test_metadata ALTER COLUMN metadata_item SET DATA TYPE jsonb USING metadata_item::jsonb;')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE test_metadata ALTER COLUMN metadata_item SET DATA TYPE json USING metadata_item::json;')
    ### end Alembic commands ###
