"""Add index for start_time and test_info_id

Revision ID: f276be9ca1be
Revises: a9b7d64c8cd7
Create Date: 2017-06-21 15:44:12.205110

"""

# revision identifiers, used by Alembic.
revision = 'f276be9ca1be'
down_revision = 'a9b7d64c8cd7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_test_test_info_id_start_time', 'test', ['test_info_id', sa.text('start_time DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_test_test_info_id_start_time', table_name='test')
    # ### end Alembic commands ###
