"""empty message

Revision ID: f568e40f06
Revises: 30e2fa0e9ec
Create Date: 2015-07-03 23:13:32.623864

"""

# revision identifiers, used by Alembic.
revision = 'f568e40f06'
down_revision = '30e2fa0e9ec'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_test_test_conclusion', table_name='test')
    op.drop_column('test', 'test_conclusion')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test', sa.Column('test_conclusion', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.create_index('ix_test_test_conclusion', 'test', ['test_conclusion'], unique=False)
    ### end Alembic commands ###
