"""Add error timestamp index

Revision ID: f8abde08cbc6
Revises: a9f4a63afe1a
Create Date: 2016-04-07 14:14:58.794575

"""

# revision identifiers, used by Alembic.
revision = 'f8abde08cbc6'
down_revision = 'a9f4a63afe1a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_error_timestamp', 'error', ['timestamp'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_error_timestamp', table_name='error')
    ### end Alembic commands ###
