apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: monitor
  name: monitor
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: monitor
    spec:
      containers:
      - env:
        - name: DATA_SOURCE_NAME
          value: postgresql://backslash@db:5432/backslash?sslmode=disable
        image: wrouesnel/postgres_exporter
        name: monitor
        ports:
        - containerPort: 9187
        resources: {}
      restartPolicy: Always
status: {}
