apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: worker
  name: worker
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: worker
    spec:
      containers:
      - args:
        - dockerize
        - -timeout
        - 3600s
        - -wait
        - tcp://rabbitmq:5672
        - pipenv
        - run
        - celery
        - -A
        - flask_app.tasks.main
        - worker
        - -B
        - --loglevel=info
        - --max-tasks-per-child=500
        env:
        - name: BACKSLASH_CELERY_BROKER_URL
          value: amqp://guest:guest@rabbitmq
        - name: BACKSLASH_DATABASE_URI
          value: postgresql://backslash@db/backslash
        - name: BACKSLASH_REDIS_SERVER
          value: redis
        - name: BACKSLASH_TRACEBACKS_PATH
          value: /uploads/tracebacks
        - name: CONFIG_DIRECTORY
          value: /conf
        image: getslash/backslash
        name: worker
        resources: {}
        volumeMounts:
        - mountPath: /conf
          name: conf
        - mountPath: /uploads
          name: uploads
      restartPolicy: Always
      volumes:
      - name: conf
        persistentVolumeClaim:
          claimName: conf
      - name: uploads
        persistentVolumeClaim:
          claimName: uploads
status: {}
