apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: api-server
  name: api-server
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: api-server
    spec:
      containers:
      - args:
        - /api-server
        - 0.0.0.0
        - "8000"
        env:
        - name: SENTRY_DSN
        image: getslash/backslash
        name: api-server
        resources: {}
      restartPolicy: Always
status: {}
