#!/usr/bin/env python
from __future__ import print_function
import argparse
import os
import subprocess
import sys

parser = argparse.ArgumentParser(usage="%(prog)s [options] args...")
parser.add_argument("--sudo", default=False, action="store_true", help="Use sudo in ansible")
parser.add_argument("-u", "--user", default=None)
parser.add_argument("host")

ROOT_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
INVENTORY_FILE = os.path.join(ROOT_DIR, ".inventory")

def main(args):
    with open(INVENTORY_FILE, "w") as inventory_file:
        print("[webservers]", file=inventory_file)
        print(args.host, file=inventory_file)
    cmd = "ansible-playbook -i {0} ansible/deploy.yml".format(INVENTORY_FILE)
    if args.host in ("127.0.0.1", "localhost"):
        cmd += " -c local"
    if args.sudo:
        cmd += " --sudo"
    if args.user:
        cmd += " -u " + args.user
    return subprocess.call(cmd, shell=True)


#### For use with entry_points/console_scripts
def main_entry_point():
    args = parser.parse_args()
    sys.exit(main(args))


if __name__ == "__main__":
    main_entry_point()
